### PR TITLE
export isLoop to allow for better combineReducers definitions

### PR DESCRIPTION
**Pull request by bdwain**
see #51

### CODE REVIEW

**Comment by bdwain** [comment]
@lukewestby any thoughts on this?

**Comment by emmby** [comment]
Seems like you also need to export none(), used by combineReducers.optimizeBatch

**Comment by emmby** [comment]
I believe you must also export none, which is used by combineReducers.optimizeBatch.  See PR https://github.com/raisemarketplace/redux-loop/pull/63

**Comment by lukewestby** [comment]
This seems totally reasonable. We can release this with the next release or sooner if it's pressing for lots of folks

**Comment by bdwain** [comment]
@lukewestby can we put this in 3.0? (or just master)

**Comment by lukewestby** [comment]
I'll merge and publish this now and also include it in 3.0

**Comment by lukewestby** [comment]
@bdwain published 2.2.0

**Comment by bdwain** [comment]
sweet thanks

**Pull request merged**
